### ISSUE TITLE
Some ideas on packaging

### ISSUE THREAD

**Issue by martijnvermaat** [mutalyzer/description-extractor#2]
Since the core algorithm is implemented in C++, I feel that it's unfortunate we're only distributing it as a Python package. I would propose to split the package into:
1. `extractor`: C++ extractor library
2. `extractor-python`: Python package wrapping the C++ library

The `extractor-python` package would be `pip`-installable (probably just under the name `extractor`.

I also feel that some of the code that's currently in Mutalyzer, should actually be in `extractor-python`. Probably all of `describe.py` and `variant.py`. It is very likely that this code provides the interface users expect rather than the C++ wrapper and it seems quite easy to move it out of Mutalyzer.

Also, I would still prefer to use Cython for `extractor-python` instead of Swig, but perhaps that's for another day.

**Comment by jfjlaros** [comment]
Agreed, but it also depends on the models.

Edit: Okay, this dependency is removed now.

**Comment by martijnvermaat** [comment]
I think we're good for now, so I'm closing this.
