### ISSUE TITLE
Missing fields in description extractor output

### ISSUE THREAD

**Issue by martijnvermaat** [mutalyzer/description-extractor#7]
When the description extractor is called with the following arguments:

```
Raw sequence: ATGATGATCAGATACAGTGTGATACAGGTAGTTAGACAA
RefSeq accession number: NM_004006.2
```

The output shows an inversion where the deleted field is filled, but the inserted field is empty.

**Comment by jkvis** [comment]
This should be fixed in: 353d910f84c1552387a13386cc569dcedca73d55
